### ISSUE TITLE
LSTM in benchmarl

### ISSUE THREAD

**Issue by majid5776** [facebookresearch/BenchMARL#103]
hello.
I eager to see dead agents(variable agents) and LSTM in your benchmark.
all the best.

**Comment by majid5776** [comment]
hi.
I don't know how to use LSTM manually in an environment, can someone please give me an example?
should I change the network architecture in the callback?
thank you.

**Comment by matteobettini** [comment]
Hey, we do not support recurrent networks currently (LSTMs), but it is a feature with high priority on the TODO list

**Comment by matteobettini** [comment]
GRU (better performing than LSTM) will be introduced in #116
