### ISSUE TITLE
make video for evaluation

### ISSUE THREAD

**Issue by majid5776** [facebookresearch/BenchMARL#104]
hello.
refer to this link
https://github.com/pytorch/rl/tree/main/sota-implementations/multiagent
when you write this script 
python mappo_ippo.py --m env.scenario_name=navigation 
wandb automatically make a video from your training.
how can I change configuration in benchmarl to make video like this one?
thank you

**Comment by matteobettini** [comment]
Benchmarl automatically makes a video.

In particular you might want to set this parameters https://github.com/facebookresearch/BenchMARL/blob/a9309159d6d46d099bd3d395ef1c80a5227b007e/benchmarl/conf/experiment/base_experiment.yaml#L78-L80 and `logges=[wandb]`

**Comment by armansouri9** [comment]
> Benchmarl automatically makes a video.
> 
> In particular you might want to set these parameters
> 
> https://github.com/facebookresearch/BenchMARL/blob/a9309159d6d46d099bd3d395ef1c80a5227b007e/benchmarl/conf/experiment/base_experiment.yaml#L78-L80
> 
> and `logges=[wandb]`

Hello, good day.
I made the changes, but the video is not being created during execution. Please advise.
Thank you.
