### ISSUE TITLE
new environments

### ISSUE THREAD

**Issue by majid5776** [facebookresearch/BenchMARL#107]
hey,
I want you please if it possible add these new envs to benchmarl envs.
I developed two new envs and I think it can make envs more realistic:
navigation and discovery with obstacles that you can change size of obstacles:
[new_envs.zip](https://github.com/user-attachments/files/16143133/new_envs.zip)

**Comment by matteobettini** [comment]
Sorry, benchmarl is not a simulator, you can add the tasks to your local version of benchmarl though. You can also contribute them to the respective simulator via a Pull Request if you think they are providing a new interesting challenge.
