### ISSUE TITLE
Error when using LSTM/GRU model

### ISSUE THREAD

**Issue by SeaingAnt** [facebookresearch/BenchMARL#121]
When launching the command line example with LSTM/GRU model for critic or actor, the sync collector breaks with the following error:

``` shell

KeyError: ('agents', 'episode_reward')

```

Generated by  the following command:

```shell
python3 benchmarl/run.py task=vmas/balance algorithm=mappo model=layers/gru model.hidden_size="125" model.mlp_layer_class="torch.nn.Linear" model.mlp_num_cells="[32,32]" model.mlp_activation_class="torch.nn.ReLU"
```

**Comment by matteobettini** [comment]
Hey! 

Thanks a lot for posting! 

Could you confirm you are using the latest github versions of benchmarl, torchrl and tensordict?

**Comment by SeaingAnt** [comment]
I'm using the pip version.

I checked again and the error appears only when using the rnn as actor. For the critic, it is ok.

**Comment by matteobettini** [comment]
The pip version of torchrl and tensordict does not work for now. We are waiting for the next release where is fixed this bug

you need the main versions as of now

**Comment by SeaingAnt** [comment]
Thank you, this works

**Comment by matteobettini** [comment]
Now rnns should work with the torchrl version from pip
