### ISSUE TITLE
An error occurred while running run.by on the command line

### ISSUE THREAD

**Issue by zqkdlmu2023** [facebookresearch/BenchMARL#128]
An error occurred while running run.by on the command line：No module named 'hydra'

**Comment by matteobettini** [comment]
`pip install hydra-core`

**Comment by matteobettini** [comment]
mmh this is very strange, upon installing `hydra-core` in your virtual env you should be able to run `import hydra`

Maybe ask in the hydra github?

do you get the same result if you run `import hydra` in a new python script?

**Comment by zqkdlmu2023** [comment]
Thank you for your answer. Running the new script will still result in errors

**Comment by matteobettini** [comment]
At this point i suggest to either ask on the hydra github or start with a fresh virtual env/ different machine

**Comment by zqkdlmu2023** [comment]
Thank you for your answer. The previous issue has been resolved, but now a new problem has arisen. We sincerely request your help！
![2024-09-11 20-37-58屏幕截图](https://github.com/user-attachments/assets/9556fc65-39bb-4a71-9de3-abdaea0cd03a)
Additionally, may I ask how to visualize the training process in Vmas.

**Comment by matteobettini** [comment]
I have to ask you to report issues in a more structured format. The screenshot is cut and does not show the error.

Evaluation renderings are displayed in the logger of choice: csv->mp4 files, wandb-> web interface

**Comment by zqkdlmu2023** [comment]
I'm sorry for my mistake.
![Uploading 2024-09-11 20-48-20屏幕截图.png…]()

**Comment by zqkdlmu2023** [comment]
![2024-09-11 20-48-20屏幕截图](https://github.com/user-attachments/assets/693a9d4b-18a9-4250-a9bb-3fc02bc794c9)

**Comment by matteobettini** [comment]
please check all your benchamrl files are from the latest main version, I am not getting this on main

**Comment by zqkdlmu2023** [comment]
Thank you for your reply. My problem has been solved. 
I am very interested in your research and would like to keep in touch with you for a long time! 
I again express my gratitude for your help!

**Comment by zqkdlmu2023** [comment]
Thank you for your reply. My problem has been solved. 
I am very interested in your research and would like to keep in touch with you for a long time! 
I again express my gratitude for your help!

**Comment by zqkdlmu2023** [comment]
Thank you for your reply. My problem has been solved. 
I am very interested in your research and would like to keep in touch with you for a long time! 
I again express my gratitude for your help!

**Comment by matteobettini** [comment]
Thank you! No problem, Glad your problem is solved, closing the issue now.
