### ISSUE TITLE
Impact of using "input" as a variable name in models code 

### ISSUE THREAD

**Issue by Giovannibriglia** [facebookresearch/BenchMARL#134]
Hi,

I've observed that in the following lines of code (as examples), the variable is named `input`. Could you please clarify why this specific name is used? Does naming the variable `input` have any implications for the model's behavior or performance?

- [mlp.py, Line 117](https://github.com/facebookresearch/BenchMARL/blob/58ff47bbbfac6de3c1b8542605ba4e83822e83af/benchmarl/models/mlp.py#L117)
- [cnn.py, Line 261](https://github.com/facebookresearch/BenchMARL/blob/58ff47bbbfac6de3c1b8542605ba4e83822e83af/benchmarl/models/cnn.py#L261)
- [gnn.py, Line 27](https://github.com/facebookresearch/BenchMARL/blob/58ff47bbbfac6de3c1b8542605ba4e83822e83af/benchmarl/models/gnn.py#L27)

Thanks for the clarification!

**Comment by matteobettini** [comment]
Why would the name of the variable impact performance?

The only consequence it has is that it obscures the built in python `inoput` fucntion (which we wouldn't use in models anyway)

**Comment by Giovannibriglia** [comment]
I had the same thought as you, but I don't think it's the best practice. However, I believe it's still acceptable.

Thanks

**Comment by matteobettini** [comment]
Yeah i agree not the best choice, but it should not have impact
