### ISSUE TITLE
The model cannot be modified during training

### ISSUE THREAD

**Issue by zqkdlmu2023** [facebookresearch/BenchMARL#138]
I am currently trying to modify the network model during training, but the following error message appears. I tried all of the network models, except mlp, and all of them had the following error:
![2024-10-10 12-32-33屏幕截图](https://github.com/user-attachments/assets/a987b30e-1de7-482d-b5a8-3b22ddb04066)

**Comment by matteobettini** [comment]
What do you mean “modifying the model during training”? Can you provide a more detailed description?

**Comment by matteobettini** [comment]
You have to install the latest torchrl and tensordict from github (source)

**Comment by zqkdlmu2023** [comment]
I tried your guidance,  but still got the same error.
![Uploading 2024-10-10 20-09-20屏幕截图.png…]()
![Uploading 2024-10-10 12-32-33屏幕截图.png…]()

**Comment by zqkdlmu2023** [comment]
![2024-10-10 20-09-20屏幕截图](https://github.com/user-attachments/assets/84108328-f99d-48b3-a681-dfa8497bd6be)
![2024-10-10 12-32-33屏幕截图](https://github.com/user-attachments/assets/10af4cc8-2618-4146-bcc5-c32a5539140b)

**Comment by matteobettini** [comment]
does it happen only with gru?
have you edited any of the components involved?

**Comment by zqkdlmu2023** [comment]
No, with the exception of MLP, replacing any other model will cause the following problems.

**Comment by zqkdlmu2023** [comment]
Got it. Now what do we do?

**Comment by matteobettini** [comment]
I would try in a fresh conda env installing the libraries from source

**Comment by zqkdlmu2023** [comment]
So,the pip version of torchrl and tensordict does not work for now?

**Comment by matteobettini** [comment]
not with lstm and gru, as explained in #121

**Comment by zqkdlmu2023** [comment]
Ok, thanks for your answer! In addition, I would like to ask you about the training details of the passage task in vmas. The following problems occurred when I was training it:
![2024-10-08 15-24-06屏幕截图](https://github.com/user-attachments/assets/06448942-e351-46a1-a3bf-72421e1c8002)

**Comment by matteobettini** [comment]
Seems like the algorithm is stuck in a local optima
