### ISSUE TITLE
VMAS simple tag MADDPG with TorchRL Tutorial - Memory map device

### ISSUE THREAD

**Issue by wangreit** [facebookresearch/BenchMARL#141]
Hi!  Thanks for sharing your work on MARL with VMAS!  The tutorial was great and included lots of details and explanations!  I have been looking for examples with non-sharing parameters between agents within the same group, as well as centralized vs decentralized training.  This tutorial is exactly what I need!  Thank you!

I was trying to test on the performance of the CPU version with PettingZoo vs GPU version with VMAS.  Apparently on replay buffer section, I am getting the error "ValueError: Memory map device other than CPU isn't supported." so I follow the instruction to cast the data by adding a line of code "replay_buffer.append_transform(lambda x: x.to(device))".  So my question is: 

Would this step slows down the training since there is a transform to change the device from CPU to GPU?  
Could we use a replay buffer other than storage=LazyMemmapStorage if there is such a limitation?  Which one could we use?

Thanks!

**Comment by matteobettini** [comment]
Hello, if this is about the torchrl tutorial could you open it there and tag me? I can reply there. I believe benchmarl is not related to this. Thanks

**Comment by wangreit** [comment]
Thank you!

https://github.com/pytorch/rl/issues/2515
