### ISSUE TITLE
Parallel collection and evaluation

### ISSUE THREAD

**Issue by gliese876b** [facebookresearch/BenchMARL#143]
Can _evaluation_loop use SyncDataCollector for non vectorized envs so that the evaluation is also parallel?

While running on Melting Pot envs, increasing n_envs_per_worker definitely improves execution time but the evaluation steps take almost 3 times longer (I have evaluation_episodes: 10) than a regular iteration since the evaluation is sequential. 

Making test_env SerialEnv could solve the issue.

**Comment by matteobettini** [comment]
Hello!

Thanks for opening this and sorry for the delay in answering.
It gives me the chance to speak about this which I wanted to do.

In vectorized environments, both collection and evaluation are done using a batch of vectorized environments.

In other environments, right now, both collection and evaluation are sequentially in the number of environments.

Collection: https://github.com/facebookresearch/BenchMARL/blob/9813807e8ddd384e0a4dc2eecc411a208078de13/benchmarl/experiment/experiment.py#L439
Evaluation: https://github.com/facebookresearch/BenchMARL/blob/9813807e8ddd384e0a4dc2eecc411a208078de13/benchmarl/experiment/experiment.py#L833

Allowing to change both of these to Parallel has long been on the TODO list: #94 

This could be as simple as changing `SerialEnv` to `ParallelEnv` but also have certain implications which have to be checked.

This is top of the todo list so I think I will get to it when i have time.

RE your specific case, in meltingpot changing the `n_envs_per_worker` should not change much as it will collect sequentially anyway. Maybe the reason evaluation is so much longer could be rendering? try to trst it with rendering disabled (it is in the experiment config)

**Comment by gliese876b** [comment]
Hello!

Thanks for the response. It is good to know that the issue is at the top of the todo list.

You are right that the collection and evaluation is done sequentially. 

Just to follow your suggestion, I changed SerialEnv to ParallelEnv yet it led to many errors so I stopped.

Also, I definitely see execution time improvements when I set n_envs_per_worker from 2 to 20. But I guess it has something to do with the reset method of meltingpot envs. 

Here is an example run of IQN on Harvest env with 10 agents with off_policy_n_envs_per_worker: 20, `evaluation_interval: 50_000`, `evaluation_episodes: 10`, `off_policy_collected_frames_per_batch: 2000`.

```
0%|          | 0/2500 [00:00<?, ?it/s].../logger.py:100: UserWarning: No episode terminated this iteration and thus the episode rewards will be NaN, this is normal if your horizon is longer then one iteration. Learning is proceeding fine.The episodes will probably terminate in a future iteration.
  warnings.warn(

mean return = nan:   0%|          | 1/2500 [05:48<241:38:32, 348.10s/it].../logger.py:100: UserWarning: No episode terminated this iteration and thus the episode rewards will be NaN, this is normal if your horizon is longer then one iteration. Learning is proceeding fine.The episodes will probably terminate in a future iteration.
  warnings.warn(

mean return = nan:   0%|          | 2/2500 [06:38<120:12:07, 173.23s/it]
mean return = nan:   0%|          | 3/2500 [07:29<81:18:35, 117.23s/it] 
mean return = nan:   0%|          | 4/2500 [08:20<63:04:10, 90.97s/it] 
mean return = nan:   0%|          | 5/2500 [09:11<53:00:30, 76.49s/it]
mean return = nan:   0%|          | 6/2500 [10:02<46:59:21, 67.83s/it]
mean return = nan:   0%|          | 7/2500 [10:52<43:04:41, 62.21s/it]
mean return = nan:   0%|          | 8/2500 [11:43<40:39:06, 58.73s/it]
mean return = nan:   0%|          | 9/2500 [12:36<39:21:00, 56.87s/it]
mean return = -88.84220123291016:   0%|          | 10/2500 [13:58<44:37:06, 64.51s/it]
mean return = nan:   0%|          | 11/2500 [14:49<41:44:54, 60.38s/it]               
mean return = nan:   0%|          | 12/2500 [15:41<39:56:15, 57.79s/it]
mean return = nan:   1%|          | 13/2500 [16:32<38:38:37, 55.94s/it]
mean return = nan:   1%|          | 14/2500 [17:24<37:44:07, 54.65s/it]
mean return = nan:   1%|          | 15/2500 [18:16<37:08:39, 53.81s/it]
mean return = nan:   1%|          | 16/2500 [19:08<36:42:25, 53.20s/it]
mean return = nan:   1%|          | 17/2500 [20:00<36:24:12, 52.78s/it]
mean return = nan:   1%|          | 18/2500 [20:52<36:17:42, 52.64s/it]
mean return = nan:   1%|          | 19/2500 [21:45<36:22:00, 52.77s/it]
mean return = -108.3295669555664:   1%|          | 20/2500 [23:08<42:33:57, 61.79s/it]
mean return = nan:   1%|          | 21/2500 [23:59<40:23:30, 58.66s/it]               
mean return = nan:   1%|          | 22/2500 [24:51<39:01:50, 56.70s/it]
mean return = nan:   1%|          | 23/2500 [25:43<38:02:08, 55.28s/it]
mean return = nan:   1%|          | 24/2500 [26:35<37:23:44, 54.37s/it]
mean return = nan:   1%|          | 25/2500 [32:32<99:44:40, 145.08s/it]  ------------------> evaluation
mean return = nan:   1%|          | 26/2500 [33:23<80:13:32, 116.74s/it]
mean return = nan:   1%|          | 27/2500 [34:13<66:28:06, 96.76s/it] 
mean return = nan:   1%|          | 28/2500 [35:04<57:02:45, 83.08s/it]
mean return = nan:   1%|          | 29/2500 [35:55<50:19:59, 73.33s/it]
mean return = -130.4561309814453:   1%|          | 30/2500 [37:15<51:42:54, 75.37s/it]
```

There is also an increase in time execution when episodes end. I guess, at the end, it cancels out the improvement on regular iterations.

**Comment by gliese876b** [comment]
Nope. Thanks for the quick responses.
Good luck!

**Comment by matteobettini** [comment]
I ll just keep this open until the feature lands

**Comment by gliese876b** [comment]
I revisited the issue and you were right that switching from SerialEnv to ParallelEnv works!

Apparently, the problem was about how I pass some env config params to env creator function. I guess ParallelEnv does not copy task config as SerialEnv do. I changed the way I pass the args and removed hydra option and now it works.

**Comment by matteobettini** [comment]
Nice! Would you be able to share your solution in a PR? Also maybe if you can open an issue in torchrl outlining where the serial and parallel differ that you did not expect

**Comment by gliese876b** [comment]
Well, in terms of collection time, ParallelEnv improves a lot.

However, after checking the results, I can see that there is a big change in terms of learning performance. I ran some more tests with the config below (on IQL), only changing SerialEnv - ParallelEnv, and somehow the learning is very poor when I use ParallelEnv.

`# Number of frames collected and each experiment iteration
off_policy_collected_frames_per_batch: 2000
# Number of environments used for collection
# If the environment is vectorized, this will be the number of batched environments.
# Otherwise batching will be simulated and each env will be run sequentially.
off_policy_n_envs_per_worker: 20
# This is the number of times off_policy_train_batch_size will be sampled from the buffer and trained over.
off_policy_n_optimizer_steps: 20
# Number of frames used for each off_policy_n_optimizer_steps when training off-policy algorithms
off_policy_train_batch_size: 128
# Maximum number of frames to keep in replay buffer memory for off-policy algorithms
off_policy_memory_size: 20000
# Number of random action frames to prefill the replay buffer with
off_policy_init_random_frames: 0`

I thought the only difference is that SerialEnv is just stepping 20 envs in sequence whereas ParallelEnv steps them in seperate processes. Note that an episode ends only if 1000 steps are taken. 

I am not sure if this originates from MeltingPot and it is due to async collection from envs.

**Comment by matteobettini** [comment]
Oh no, that does not sound good. I feared something like this. I'll need to take a look

We need to identify where this deviation first occurs.

Maybe the first apporoach would be to test with a non-learned deterministic policy and see if the result is different.

**Comment by gliese876b** [comment]
I think it is not about learning but logging.

When I run with 2 envs, I realize that episode_reward metric for an agent gets either integer values or values with 0.5 with SerialEnv whereas it has values like 23.2175006866455 with ParallelEnv. 

I checked the batches in either case, and saw a strange difference. For episodes of 1000 steps,
- In SerialEnv case, the ('next', 'done') key returns a tensor of 999 False and 1 True at the end
- In ParallelEnv case, the same key returns a tensor of 1000 True values.
I guess the batch is split by these done values, so episode reward is averaged over 1000 values in ParallelEnv while it is averaged over 2 in SerialEnv.

I pinpointed the problem here: If I remove TransformedEnv, the done keys return as expected.

Any ideas on the reason?

**Comment by matteobettini** [comment]
Do you know what specific transform causes this to happen?  ccing @vmoens

**Comment by gliese876b** [comment]
I tried passing an empty list of Transforms but it led to other errors.

MeltingpotTask has additional transforms but I am not sure they are the reason.

Maybe it is about reset keys? Or done_specs?

**Comment by matteobettini** [comment]
Mhh i would need a bit more systematic report. If you could pinpoint with more granularity what component causes the deviation I can take a look. A reprod script would also help although I know it is time consuming. Maybe you can tell me what are the minimal changes you did to benchmarl main to reach your state

**Comment by gliese876b** [comment]
I tried a fresh clone in a fresh conda env with the following script;

`python3 benchmarl/run.py algorithm=iql task=meltingpot/coins model=layers/mp_cnn model@critic_model=layers/mp_cnn`

where mp_cnn contains

`name: cnn

mlp_num_cells: [128]
mlp_layer_class: torch.nn.Linear
mlp_activation_class: torch.nn.Tanh
mlp_activation_kwargs: null
mlp_norm_class: null
mlp_norm_kwargs: null

cnn_num_cells: [32, 128]
cnn_kernel_sizes: [6, 11]
cnn_strides: [8, 1]
cnn_paddings: [1, 0]
cnn_activation_class: torch.nn.ReLU
cnn_activation_kwargs: null
cnn_norm_class: null
cnn_norm_kwargs: null`

However now this gives the following error:

`Traceback (most recent call last):
  File "/home/singh/Desktop/tmp/BenchMARL/benchmarl/run.py", line 37, in hydra_experiment
    experiment = load_experiment_from_hydra(cfg, task_name=task_name)
  File "/home/singh/Desktop/tmp/BenchMARL/benchmarl/hydra_config.py", line 43, in load_experiment_from_hydra
    return Experiment(
  File "/home/singh/Desktop/tmp/BenchMARL/benchmarl/experiment/experiment.py", line 339, in __init__
    self._setup()
  File "/home/singh/Desktop/tmp/BenchMARL/benchmarl/experiment/experiment.py", line 359, in _setup
    self._setup_task()
  File "/home/singh/Desktop/tmp/BenchMARL/benchmarl/experiment/experiment.py", line 416, in _setup_task
    test_env = self.task.get_env_fun(
  File "/home/singh/Desktop/tmp/BenchMARL/benchmarl/environments/meltingpot/common.py", line 87, in <lambda>
    return lambda: MeltingpotEnv(
  File "/home/singh/.local/lib/python3.10/site-packages/torchrl/envs/common.py", line 171, in __call__
    instance: EnvBase = super().__call__(*args, **kwargs)
  File "/home/singh/.local/lib/python3.10/site-packages/torchrl/envs/libs/meltingpot.py", line 574, in __init__
    super().__init__(
  File "/home/singh/.local/lib/python3.10/site-packages/torchrl/envs/libs/meltingpot.py", line 197, in __init__
    super().__init__(**kwargs)
  File "/home/singh/.local/lib/python3.10/site-packages/torchrl/envs/common.py", line 3126, in __init__
    self._env = self._build_env(**kwargs)  # writes the self._env attribute
  File "/home/singh/.local/lib/python3.10/site-packages/torchrl/envs/libs/meltingpot.py", line 590, in _build_env
    from meltingpot import substrate as mp_substrate
  File "/home/singh/.local/lib/python3.10/site-packages/meltingpot/__init__.py", line 18, in <module>
    from meltingpot import bot
  File "/home/singh/.local/lib/python3.10/site-packages/meltingpot/bot.py", line 18, in <module>
    from meltingpot import substrate
  File "/home/singh/.local/lib/python3.10/site-packages/meltingpot/substrate.py", line 21, in <module>
    from meltingpot.utils.substrates import substrate
  File "/home/singh/.local/lib/python3.10/site-packages/meltingpot/utils/substrates/substrate.py", line 19, in <module>
    import chex
  File "/home/singh/.local/lib/python3.10/site-packages/chex/__init__.py", line 17, in <module>
    from chex._src.asserts import assert_axis_dimension
  File "/home/singh/.local/lib/python3.10/site-packages/chex/_src/asserts.py", line 26, in <module>
    from chex._src import asserts_internal as _ai
  File "/home/singh/.local/lib/python3.10/site-packages/chex/_src/asserts_internal.py", line 34, in <module>
    from chex._src import pytypes
  File "/home/singh/.local/lib/python3.10/site-packages/chex/_src/pytypes.py", line 53, in <module>
    Shape = jax.core.Shape
  File "/home/singh/.local/lib/python3.10/site-packages/jax/_src/deprecations.py", line 52, in getattr
    raise AttributeError(message)
AttributeError: jax.core.Shape is deprecated. Use Shape = Sequence[int | Any].`

I'll continue debugging on my own branch to make ParallelEnv work for now.

**Comment by gliese876b** [comment]
Here is an odd observation: when I change the sampling_device from 'cpu' to 'cuda', the done keys are correct as in the SerialEnv setting.

In fact, when I set `sampling_device='cpu'`  and `collect_with_grad=True` and add below prints at the end of `_setup_collector`

`print("------1--------")`
`print(self.env_func().to(self.config.sampling_device).rollout(max_steps=1000).get(('next', 'done')))`
`print("------2--------")`
`print(self.env_func().rollout(max_steps=1000).get(('next', 'done')))`

It prints

`------1--------`
```
tensor([[[True],
         [True],
         [True],
         ...,
         [True],
         [True],
         [True]],

        [[True],
         [True],
         [True],
         ...,
         [True],
         [True],
         [True]]])
```
`------2--------`
```
tensor([[[False],
         [False],
         [False],
         ...,
         [False],
         [False],
         [ True]],

        [[False],
         [False],
         [False],
         ...,
         [False],
         [False],
         [ True]]])
```


I guess casting the rollout to the sampling device applies a transformation that messes up the done keys.

**Comment by gliese876b** [comment]
Ok. I got the problem solved.

I was using a custom wrapper for MeltingPot envs and I realize that I did not pass device parameter to the constructor. As I did, this problem vanishes. I guess the mismatch was the reason.

**Comment by matteobettini** [comment]
Really nice to hear! Feel free to make a PR to enable users to choose parallel or serial if this is easy

**Comment by gliese876b** [comment]
Sorry that I couldn't respond before.

Thanks for the PR!

I wanted parallel collection since I had a model with an LSTM layer. Now with ParallelEnv, it gives an error;

```
  File "/home/adem/miniconda3/envs/bench_env/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/adem/miniconda3/envs/bench_env/lib/python3.11/site-packages/torchrl/_utils.py", line 669, in run
    return mp.Process.run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adem/miniconda3/envs/bench_env/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adem/miniconda3/envs/bench_env/lib/python3.11/site-packages/torchrl/envs/batched_envs.py", line 2215, in _run_worker_pipe_shared_mem
    "next", next_shared_tensordict.select(*next_td_passthrough_keys)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adem/miniconda3/envs/bench_env/lib/python3.11/site-packages/tensordict/base.py", line 9275, in select
    result = self._select(*keys, inplace=inplace, strict=strict)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adem/miniconda3/envs/bench_env/lib/python3.11/site-packages/tensordict/_td.py", line 3089, in _select
    source[key] = source[key]._select(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/adem/miniconda3/envs/bench_env/lib/python3.11/site-packages/tensordict/_td.py", line 3077, in _select
    val = self._get_str(key, default=None if not strict else NO_DEFAULT)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adem/miniconda3/envs/bench_env/lib/python3.11/site-packages/tensordict/_td.py", line 2489, in _get_str
    return self._default_get(first_key, default)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adem/miniconda3/envs/bench_env/lib/python3.11/site-packages/tensordict/base.py", line 4973, in _default_get
    raise KeyError(
KeyError: 'key "_hidden_lstm_h_1" not found in TensorDict with keys [\'observation\', \'reward\']'
```

I checked the arguments of ParallelEnv but couldn't find a solution yet.

**Comment by matteobettini** [comment]
Got it! I'll try to investigate

**Comment by gliese876b** [comment]
Here is further info;

BatchedEnv from TorchRL collects the keys from the next field of the tensordict as the keys to be passed between the processes. 

If I make the data variable empty in the below line;
[https://github.com/pytorch/rl/blob/91064bc27d018fc8c489b5d91fa5d39cdcc18000/torchrl/envs/batched_envs.py#L1747](url)
the error disappears and learning is fine with a model of LSTM.

Keys like "_hidden_lstm_h_1" are expected in the tensordict from envs since LSTM model puts them there but somehow the values are missing when the actual transfer is to occur. If I comment the below lines;
[https://github.com/facebookresearch/BenchMARL/blob/271edee9aa6fe03d1c91b98646e30dde833f2f6c/benchmarl/models/lstm.py#L501](url)
the error again disappears and the learning is fine.

Can you check if the implementation of the LSTM layer really requires these?

**Comment by matteobettini** [comment]
What exactly did you comment out? Just 501?

The LSTM needs to write those values during execution as they have to be read in the next step, during training they are not needed as we process a time batch and not a single step

**Comment by gliese876b** [comment]
I understand that LSTM needs the values to work properly. 
If I commented out the if clause with its body in 501 in lstm.py or make data empty in 1747 in batched_envs.py, the error disappears. I did these just to identify the origin of the problem.

So, these values are needed to be passed between processes (copies of env) but they don't exist in the tensordict that is passed to _step() method in BatchedEnv.

Thanks for the help btw!

**Comment by matteobettini** [comment]
@gliese876b try now, should work

**Comment by gliese876b** [comment]
@matteobettini, thanks!

I run a test with the same model configs on the branch after your commits.

It gets the error below;

```
Traceback (most recent call last):
  File "/home/singh/Desktop/tmp/BenchMARL/benchmarl/run.py", line 37, in hydra_experiment
    experiment = load_experiment_from_hydra(cfg, task_name=task_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/singh/Desktop/tmp/BenchMARL/benchmarl/hydra_config.py", line 43, in load_experiment_from_hydra
    return Experiment(
           ^^^^^^^^^^^
  File "/home/singh/Desktop/tmp/BenchMARL/benchmarl/experiment/experiment.py", line 350, in __init__
    self._setup()
  File "/home/singh/Desktop/tmp/BenchMARL/benchmarl/experiment/experiment.py", line 372, in _setup
    self._setup_collector()
  File "/home/singh/Desktop/tmp/BenchMARL/benchmarl/experiment/experiment.py", line 514, in _setup_collector
    self.collector = SyncDataCollector(
                     ^^^^^^^^^^^^^^^^^^
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/site-packages/torchrl/collectors/collectors.py", line 739, in __init__
    self._make_shuttle()
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/site-packages/torchrl/collectors/collectors.py", line 763, in _make_shuttle
    self._shuttle = self.env.reset()
                    ^^^^^^^^^^^^^^^^
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/site-packages/torchrl/envs/common.py", line 2165, in reset
    tensordict_reset = self._reset(tensordict, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/site-packages/torchrl/envs/transforms/transforms.py", line 814, in _reset
    tensordict_reset = self.base_env._reset(tensordict, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/site-packages/torchrl/envs/batched_envs.py", line 63, in decorated_fun
    self._start_workers()
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/site-packages/torchrl/envs/batched_envs.py", line 1436, in _start_workers
    process.start()
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/site-packages/torchrl/data/utils.py", line 244, in __getstate__
    return cloudpickle.dumps((self.fn, self.kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/site-packages/cloudpickle/cloudpickle.py", line 1529, in dumps
    cp.dump(obj)
  File "/home/singh/miniconda3/envs/tmp_env/lib/python3.11/site-packages/cloudpickle/cloudpickle.py", line 1295, in dump
    return super().dump(obj)
           ^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'dmlab2d.dmlab2d_pybind.Lab2d' object
```

This is related to meltingpot using lab2d as backend. 
Following a suggestion online, I used

```
import multiprocessing
multiprocessing.set_start_method("fork", force=True)
```

and this solves the issue although it is restricted to Unix-like systems. I am running on Ubuntu at the moment.

**Comment by matteobettini** [comment]
Mmmh i don't get this error, can you confirm you are using just the code from my PR?

**Comment by matteobettini** [comment]
This is strange... it only happens if ther eis an rnn in the sequence

**Comment by matteobettini** [comment]
I think I got it. Some weird lambda thing. Try now, fingers crossed

**Comment by gliese876b** [comment]
Yes, no errors, working fine with a model of LSTM on ParallelEnv.

Great work!

Thank you so much. Now that the collection is parallel, this will save a lot of time.

**Comment by Fool-Yang** [comment]
Hello. I am trying to run my own env with parallel collection.
I the following error:
```
    def get_env_fun(
        self,
        num_envs: int,
        continuous_actions: bool,
        seed: Optional[int],
        device: DEVICE_TYPING,
    ) -> Callable[[], EnvBase]:
        return lambda: PettingZooWrapper(
            MyEnv(),
            device=device,
            return_state=False,
            group_map=None,
            use_mask=False,
            categorical_actions=True, # If your env has discrete actions, they need to be categorical (TorchRL can help with this)
            seed=seed,
            done_on_any=True,
            **self.config, # Pass the loaded config (this is what is in your yaml)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        )
```

> TypeError: torchrl.envs.libs.pettingzoo.PettingZooWrapper() argument after ** must be a mapping, not NoneType

The following will work:
```
    def get_env_fun(
        ...
    ) -> Callable[[], EnvBase]:
        return lambda: PettingZooWrapper(
            ...
            **{}, # Pass the loaded config (this is what is in your yaml)
        )
```
But this won't work:

```
    def get_env_fun(
        ...
    ) -> Callable[[], EnvBase]:
        self.config = {}
        return lambda: PettingZooWrapper(
            ...
            **self.config, # Pass the loaded config (this is what is in your yaml)
        )
```

I don't understand what is the cause of the problem and why the first one works but not the second. I assume I can run the experiments fine with {}.

**Comment by matteobettini** [comment]
This is a torchrl requirement, you need to

https://github.com/facebookresearch/BenchMARL/blob/54721f77f6b7e8c2af5933c81276f1289cb47bb2/benchmarl/environments/pettingzoo/common.py#L39


And it will work

**Comment by Fool-Yang** [comment]
> This is a torchrl requirement, you need to
> 
> [BenchMARL/benchmarl/environments/pettingzoo/common.py](https://github.com/facebookresearch/BenchMARL/blob/54721f77f6b7e8c2af5933c81276f1289cb47bb2/benchmarl/environments/pettingzoo/common.py#L39)
> 
> Line 39 in [54721f7](/facebookresearch/BenchMARL/commit/54721f77f6b7e8c2af5933c81276f1289cb47bb2)
> 
>  config = copy.deepcopy(self.config) 
> And it will work

Totally worked! Thank you for the super quick response.

**Comment by matteobettini** [comment]
Yeah that is currently the case, eventually i ll get around to it.

For now you can just evaluate less or less frequently
