### ISSUE TITLE
Properly Citing BenchMARL

### ISSUE THREAD

**Issue by SashaBoguraev** [facebookresearch/BenchMARL#38]
I'm currently writing up findings for a study which utilized BenchMARL, and couldn't find any instructions in the repo on how to properly cite the package in my work, nor an associated paper to cite in its stead. Is there a desired method for us to give proper credit to the software, or would just mentioning it somewhere in our paper suffice?

**Comment by matteobettini** [comment]
Thanks you for raising this and for using the library.

I have added in #39 references on how the repo can be cited.
As of now the citation is for the software only, but we will udate it with the arxiv paper as soon as that is available.

Here you can fing the instructions https://github.com/facebookresearch/BenchMARL#citing-benchmarl

**Comment by matteobettini** [comment]
In [ca2b935](https://github.com/facebookresearch/BenchMARL/commit/ca2b9354d913f892a6e389e4fd38f15eea32e9e6) I have updated the citation to the respective arXiv paper https://arxiv.org/abs/2312.01472
