### ISSUE TITLE
Vmas/transport task fails to start.

### ISSUE THREAD

**Issue by balamir53** [facebookresearch/BenchMARL#43]
Starting a training via cli 'python benchmarl/run.py algorithm=mappo task=vmas/transport' gives the error after a while (changing max steps in transport.yaml belates the raise error function hit): 

BenchMARL/.venv/lib/python3.10/site-packages/torchrl/envs/common.py", line 1527, in _reset_check_done
    raise RuntimeError(
RuntimeError: Env done entry 'done' was (partially) True after reset on specified '_reset' dimensions. This is not allowed.

**Comment by matteobettini** [comment]
Hey, thanks for posting this!

Could you share your versions of vmas and torchrl?

**Comment by balamir53** [comment]
vmas==1.3.3
torchrl==0.2.1

**Comment by matteobettini** [comment]
I found the issue in TorchRL and opened an issue for you.
https://github.com/pytorch/rl/issues/1806

I will also fix this in VMAS and make sure the package is never spawned on the goal

**Comment by matteobettini** [comment]
The fix in vmas is https://github.com/proroklab/VectorizedMultiAgentSimulator/commit/b434185c8f205d34186b00d23cf4a9e122195863

If you use VMAS main the error should (hopefully) not occour anymore

**Comment by balamir53** [comment]
Yeah, that fixed my problem. Thanks.

**Comment by matteobettini** [comment]
Closing this as solved both in vmas and torchrl
