### ISSUE TITLE
Visualization 

### ISSUE THREAD

**Issue by prinshul** [facebookresearch/BenchMARL#50]
Hi

For how many runs the plot std dev is taken (the shaded part in the plots)? 
And these different runs are with different seeds?

![environemnt_sample_efficiency_curves](https://github.com/facebookresearch/BenchMARL/assets/13760669/33811c7c-c9ae-4ad4-8d9d-4790abcc3cbf)

**Comment by matteobettini** [comment]
The VMAS benchmark have been run with 3 seeds for each experiment.

 You should be able to see the number of runs on  wandb.
