### ISSUE TITLE
Plotting

### ISSUE THREAD

**Issue by prinshul** [facebookresearch/BenchMARL#63]
Hi,

Is it possible to run multiple expmnts. with tuned hyperparameters like below?
python fine_tuned/vmas/vmas_run.py -m algorithm=mappo,maddpg task=vmas/balance seed=0,1,2
(Two algos on balance with three seeds)

If not, can you suggest how multiple runs can be plotted in a single plot if I have .json in "marl_eval" format for each run? I tried but was unable to get a single plot with multiple json files. 

Thanks.

**Comment by matteobettini** [comment]
Yes it is possible and it is done exactly like that. 

If you look at https://github.com/facebookresearch/BenchMARL/blob/6aae619360702263f36096ca0ea40960abf88a3c/benchmarl/eval_results.py there are utils to plot results given the folder of a hydra multirun
